---
title: "Calculations final"
author: "Mitchell Ardolf"
date: "10/9/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Evans Calculations



```{r echo=FALSE}

# Plots a digit as text matrix on the terminal
plot_text <- function(image) {
  a_digit <- matrix(image, nrow=28)
  even_pos <- seq(4,24,2)
  (a_digit[even_pos,even_pos])
}

# This function outputs a contrasted image 
# Notice an image is represented as a vector of 784 number from 0 to 255.
contrast_digit <- function(image){
  dark_idx = (image>128)
  image[dark_idx]=255   # Turn dark pixel indexes to 255
  image[!dark_idx]=0    # Turn non-dark pixel indexes to 0 (we use symbol !)
  return (image)
}

# Plots a digit as an image
plot_digit <- function(image) {
  a_digit <- matrix(image, nrow=28)
  image(a_digit[,28:1])
}

# This function outputs a contrasted image 
# Notice an image is represented as a vector of 784 number from 0 to 255.
contrast_digit <- function(image){
  dark_idx = (image>128)
  image[dark_idx]=255   # Turn dark pixel indexes to 255
  image[!dark_idx]=0    # Turn non-dark pixel indexes to 0 (we use symbol !)
  return (image)
}

# This function calculates the number of dark pixels from an image
# Notice an image is represented as a vector of 784 number from 0 to 255.
count_dark_pixels <- function (image){
  dark_idx <- image>128
  num_pixels <- sum(dark_idx)
  return(num_pixels)
}

count_light_pixels <- function (image){
  light_idx <- image<128
  num_pixels <- sum(light_idx)
  return(num_pixels)
}

# This function returns a matrix with all the images corresponding to a digit (0-9) 
# from your mnist training dataset.
# The matrix will have 784 columns and the number of rows corresponds to the
# number of images
get_image_train_digit <- function (digit) {
  idx <- mnist$train$labels==digit
  images <- mnist$train$images[idx,]
  return (images)
}

# This function returns a matrix with all the images corresponding to a digit (0-9) 
# from your mnist testing dataset.
# The matrix will have 784 columns and the number of rows corresponds to the
# number of images
get_image_test_digit <- function (digit) {
  idx <- mnist$test$labels==digit
  images <- mnist$test$images[idx,]
  return (images)
}
```

```{r}
library(dslabs)
mnist <- read_mnist("~/Mscs 341 F23/Class/Data")

# Plots a digit as an image
plot_digit <- function(image) {
  a_digit <- matrix(image, nrow=28)
  image(a_digit[,28:1])
}

# This function returns a matrix with all the images corresponding to a digit (0-9) 
# The matrix will have 784 columns and the number of rows corresponds to the
# number of images
get_image_digit_train <- function (digit) {
  idx <- mnist$train$labels==digit
  images <- mnist$train$images[idx,]
  return (images)
}
test <- get_image_digit(4)



get_image_digit_test <- function (digit) {
  idx <- mnist$test$labels==digit
  images <- mnist$test$images[idx,]
  return (images)
}

contrast_digit <- function(image){
  dark_idx = (image>128)
  image[dark_idx]=255   # Turn dark pixel indexes to 255
  image[!dark_idx]=0    # Turn non-dark pixel indexes to 0 (we use symbol !)
  return (image)
}



# Create a sample matrix


```
functions 

```{r}
get_width <- function(image){ 
  #the function takes an image and looks at all columns those columns that contain pixels are counted.
  a_digit <- matrix(image, nrow = 28)
  adigit <- a_digit[, 28:1]
  i <- 1
  j <- 0

  while (i <= 28) {
    if (sum(adigit[i, ]) > 0) {
      j <- j + 1
    }
    
    i <- i + 1
  }
  return(j)
  
}



get_size <- function(images){
  
  n_images <- nrow(images)
  
  # We use a for loop to calculate the darkness of each digit
  size_val <- vector(mode="integer", length=n_images)
  for (i in 1:n_images) {
    size_val[i] = get_width(images[i,]) #calcultate the darkness of each image provided 
  }
  return (size_val)
}





count_dark_pixels <- function (image){ # This function counts the dark pixels in the loop 
  dark_idx <- image>128
  num_pixels <- sum(dark_idx)
  return(num_pixels)
}

get_num_pixels <- function(images){
  # We get all images corresponding to a digit

  n_images <- nrow(images)
  
  # We use a for loop to calculate the ink of each digit
  dark <- vector(mode="integer", length=n_images)
  for (i in 1:n_images) {
    dark[i] = count_dark_pixels(images[i, 1:392])
  }
  return (dark)
}



contrast <- function(images){
  # We get all images corresponding to a digit

  n_images <- nrow(images)
  
  # We use a for loop to calculate the ink of each digit
  dark <- vector(mode="integer", length=n_images)
  jeff<- vector(mode="integer", length=n_images)
  for (i in 1:n_images) {
    #jeff[i] = contrast_digit(images[i, ])
    dark[i] = count_dark_pixels(contrast_digit(images[i, 1:392]))
  }
  return (dark)
}


get_size_light <- function(images){
  
  n_images <- nrow(images)
  
  # We use a for loop to calculate the darkness of each digit
  size_val <- vector(mode="integer", length=n_images)
  for (i in 1:n_images) {
    size_val[i] = get_width(contrast_digit(images[i,])) #width of the image
  }
  return (size_val)
}







```

Getting data and running the functions 
```{r}
library(dplyr)

#get all ones and fours for training 
image1_train <- get_image_digit_train(1)
image4_train <- get_image_digit_train(4)

# get row numbers (indexes) for 1s and 4s in training. -Mitch
train_count_1_bool <- mnist$train$labels==1 # get boolean of 1s in train
length1_train <- sum(train_count_1_bool) # get number of 1s for the loop
idx1_train <- vector(mode = "integer", length = length1_train)
n=1
for (i in 1:60000){
  
  if (train_count_1_bool[i] == TRUE){
    if (idx1_train[n] != 0){
      n = n+1
    }
    idx1_train[n] <- i
    
  }
  
}

train_count_4_bool <- mnist$train$labels==4 # get boolean of 4s in train
length4_train <- sum(train_count_4_bool) # get number of 4s for the loop
idx4_train <- vector(mode = "integer", length = length4_train)
n=1
for (i in 1:60000){
  
  if (train_count_4_bool[i] == TRUE){
    if (idx4_train[n] != 0){
      n = n+1
    }
    idx4_train[n] <- i
    
  }
  
}


#get all ones and fours for testing 
image1_test <- get_image_digit_test(1)
image4_test <- get_image_digit_test(4)

# get row numbers (indexes) for 1s and 4s in training. -Mitch
test_count_1_bool <- mnist$test$labels==1 # get boolean of 1s in test
length1_test <- sum(test_count_1_bool) # get number of 1s for the loop
idx1_test <- vector(mode = "integer", length = length1_test)
n=1
for (i in 1:10000){
  
  if (test_count_1_bool[i] == TRUE){
    if (idx1_test[n] != 0){
      n = n+1
    }
    idx1_test[n] <- i
    
  }
  
}

test_count_4_bool <- mnist$test$labels==4 # get boolean of 4s in test
length4_test <- sum(test_count_4_bool) # get number of 4s for the loop
idx4_test <- vector(mode = "integer", length = length4_test)
n=1
for (i in 1:60000){
  
  if (test_count_4_bool[i] == TRUE){
    if (idx4_test[n] != 0){
      n = n+1
    }
    idx4_test[n] <- i
    
  }
  
}

#get all ones and fours for training 
image1_train <- get_image_digit_train(1)
image4_train <- get_image_digit_train(4)

#get all ones and fours for testing 
image1_test <- get_image_digit_test(1)
image4_test <- get_image_digit_test(4)





#calculate features for training get the number of pixels for ones 
image_1_dark_train <- get_num_pixels(image1_train)
image_1_light_train <- contrast(image1_train)


#calculate features for training get size of the image for ones 
image_1_size_train <- get_size(image1_train)
image_1_size_light_train <- get_size_light(image1_train)

#calculate features for testing get the number of pixels for ones 
image_1_dark_test <- get_num_pixels(image1_test)
image_1_light_test <- contrast(image1_test)

#calculate features for testing get size of the image for ones 
image_1_size_test <- get_size(image1_test)
image_1_size_light_test <- get_size_light(image1_test)


#combine the tables to get our training and testing tables for ones training
combined_table_1_train <- data.frame(Size = image_1_size_train, Size_Contrast = image_1_size_light_train,   Dark = image_1_dark_train,  Number = 1)
#testing
combined_table_1_test <- data.frame(Size = image_1_size_test, Size_Contrast = image_1_size_light_test,    Dark = image_1_dark_test,  Number = 1)


#calculate features for training get the number of pixels for ones  

#image_4_dark_train <- get_num_pixels(image4_train)
#image_4_size_train <- get_size(image4_train)

#calculate features for training get the number of pixels for fours
image_4_dark_train <- get_num_pixels(image4_train)
image_4_light_train <- contrast(image4_train)

#calculate features for training get size of the image for fours 
image_4_size_train <- get_size(image4_train)
image_4_size_light_train <- get_size_light(image4_train)



#image_4_dark_test <- get_num_pixels(image4_test)
#image_4_size_test <- get_size(image4_test)


#calculate features for testing get the number of pixels for fours 
image_4_dark_test <- get_num_pixels(image4_test)
image_4_light_test <- contrast(image4_test)

#calculate features for testing get size of the image for fours 
image_4_size_test <- get_size(image4_test)
image_4_size_light_test <- get_size_light(image4_test)



#combined_table_4_train <- data.frame(Size = image_4_size_train, Dark = image_4_dark_train, Number = 4)
#combined_table_4_test <- data.frame(Size = image_4_size_test, Dark = image_4_dark_test, Number = 4)

#combine the tables to get our training and testing tables for ones training
combined_table_4_train <- data.frame(Size = image_4_size_train, Size_Contrast = image_4_size_light_train,  Dark = image_4_dark_train,  Number = 4)
#testing
combined_table_4_test <- data.frame(Size = image_4_size_test, Size_Contrast = image_4_size_light_test, Dark = image_4_dark_test,  Number = 4)



combined_train <- bind_rows(combined_table_1_train, combined_table_4_train)
combined_test <- bind_rows(combined_table_1_test, combined_table_4_test)

```


sampling our table 
```{r}

set.seed(123)
sampled_data_train <- combined_train %>% sample_n(800, replace = FALSE)
sampled_data_test <- combined_test %>% sample_n(200, replace = FALSE)
```


```{r}
#need separate paths for separate data sets. -Mitch
file_path_test <- "~/Mscs 341 F23/Project/Mitch, Evan, Adam/Data/sampled_data_test.csv"
file_path_train <- "~/Mscs 341 F23/Project/Mitch, Evan, Adam/Data/sampled_data_train.csv"

# Write the files -Mitch
write.csv(sampled_data_train, file = file_path_train)
write.csv(sampled_data_test, file = file_path_test)



```
